[environments.development]
url = "jdbc:postgresql://ep-purple-bar-edzrpa7p.database.uksouth.azuredatabricks.net/databricks_postgres?sslmode=require"
user = "stephanie.herr@red-gate.com"
password = "${localSecret.Flyway Desktop 595b0795-e793-406e-b661-b232f5ed2983}"
schemas = [ "public" ]
provisioner = "none"

[environments.shadow]
url = "jdbc:postgresql://ep-green-morning-edi6q24g.database.uksouth.azuredatabricks.net/databricks_postgres?sslmode=require"
user = "stephanie.herr@red-gate.com"
password = "${localSecret.Flyway Desktop dd559caa-38e2-4570-a145-c7b893dda70b}"
schemas = [ "public" ]
provisioner = "none"

[environments.test]
user = "stephanie.herr@red-gate.com"
password = "${localSecret.Flyway Desktop 28ff1e49-5362-4b84-9409-92eb7183ab93}"

[environments.prod]
user = "stephanie.herr@red-gate.com"
password = "${localSecret.Flyway Desktop a1dde613-e56b-4bba-a436-0e1114fde03a}"
