databaseType = "PostgreSql"
id = "2b4bb9fa-e91a-416a-b594-5e8107add0c2"
name = "Databricks Lakebase"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

[flywayDesktop]
enableMigrations = true
developmentEnvironment = "development"
shadowEnvironment = "shadow"
deploymentPlatform = "Bash"

  [flywayDesktop.generate]
  undoScripts = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

  [[redgateCompare.staticDataTables]]
  schema = "public"
  table = "playing_with_lakebase"

[environments.test]
url = "jdbc:postgresql://ep-snowy-fire-edmug8v7.database.uksouth.azuredatabricks.net/databricks_postgres?sslmode=require"
schemas = [ "public" ]

[environments.prod]
url = "jdbc:postgresql://ep-aged-block-edrgs8pn.database.uksouth.azuredatabricks.net/databricks_postgres?sslmode=require"
schemas = [ "public" ]
displayName = "prod"
