-- Script generated by Redgate Compare v1.62.3.4970


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.store...';END$$;
CREATE TABLE public.store (
    store_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    manager_staff_id integer,
    address_id integer NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.store ADD CONSTRAINT store_pkey PRIMARY KEY (store_id);
ALTER TABLE public.store OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.store TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.store TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.store TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.store TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.store TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.staff...';END$$;
CREATE TABLE public.staff (
    staff_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(45) NOT NULL,
    last_name character varying(45) NOT NULL,
    address_id integer NOT NULL,
    email character varying(50),
    store_id integer NOT NULL,
    active boolean NOT NULL DEFAULT true,
    username character varying(16) NOT NULL,
    password character varying(40),
    last_update timestamp with time zone NOT NULL DEFAULT now(),
    picture bytea
);
ALTER TABLE public.staff ADD CONSTRAINT staff_pkey PRIMARY KEY (staff_id);
ALTER TABLE public.staff OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.staff TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.staff TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.staff TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.staff TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.staff TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.rental...';END$$;
CREATE TABLE public.rental (
    rental_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    rental_date timestamp with time zone NOT NULL,
    inventory_id integer NOT NULL,
    customer_id integer NOT NULL,
    return_date timestamp with time zone,
    staff_id integer NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.rental ADD CONSTRAINT rental_pkey PRIMARY KEY (rental_id);
ALTER TABLE public.rental OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.rental TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.rental TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.rental TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.rental TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.rental TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.payment...';END$$;
CREATE TABLE public.payment (
    payment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    staff_id integer NOT NULL,
    rental_id integer NOT NULL,
    amount numeric(5,2) NOT NULL,
    payment_date timestamp with time zone NOT NULL
);
ALTER TABLE public.payment ADD CONSTRAINT payment_pkey PRIMARY KEY (payment_id);
ALTER TABLE public.payment OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.payment TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.payment TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.payment TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.payment TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.payment TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.language...';END$$;
CREATE TABLE public.language (
    language_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(20) NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.language ADD CONSTRAINT language_pkey PRIMARY KEY (language_id);
ALTER TABLE public.language OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.language TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.language TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.language TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.language TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.language TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.inventory...';END$$;
CREATE TABLE public.inventory (
    inventory_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    film_id integer NOT NULL,
    store_id integer NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.inventory ADD CONSTRAINT inventory_pkey PRIMARY KEY (inventory_id);
ALTER TABLE public.inventory OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.inventory TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.inventory TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.inventory TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.inventory TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.inventory TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film_category...';END$$;
CREATE TABLE public.film_category (
    film_id integer NOT NULL,
    category_id integer NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.film_category ADD CONSTRAINT film_category_pkey PRIMARY KEY (film_id, category_id);
ALTER TABLE public.film_category OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.film_category TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.film_category TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.film_category TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.film_category TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.film_category TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film_actor...';END$$;
CREATE TABLE public.film_actor (
    actor_id integer NOT NULL,
    film_id integer NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.film_actor ADD CONSTRAINT film_actor_pkey PRIMARY KEY (actor_id, film_id);
ALTER TABLE public.film_actor OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.film_actor TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.film_actor TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.film_actor TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.film_actor TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.film_actor TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.customer...';END$$;
CREATE TABLE public.customer (
    customer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    store_id integer NOT NULL,
    first_name character varying(45) NOT NULL,
    last_name character varying(45) NOT NULL,
    email character varying(50),
    address_id integer NOT NULL,
    activebool boolean NOT NULL DEFAULT true,
    create_date date NOT NULL DEFAULT ('now'::text)::date,
    last_update timestamp with time zone DEFAULT now(),
    active integer
);
ALTER TABLE public.customer ADD CONSTRAINT customer_pkey PRIMARY KEY (customer_id);
ALTER TABLE public.customer OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.customer TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.customer TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.customer TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.customer TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.customer TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.country...';END$$;
CREATE TABLE public.country (
    country_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    country character varying(50) NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.country ADD CONSTRAINT country_pkey PRIMARY KEY (country_id);
ALTER TABLE public.country OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.country TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.country TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.country TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.country TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.country TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.city...';END$$;
CREATE TABLE public.city (
    city_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city character varying(50) NOT NULL,
    country_id integer NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.city ADD CONSTRAINT city_pkey PRIMARY KEY (city_id);
ALTER TABLE public.city OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.city TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.city TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.city TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.city TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.city TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.category...';END$$;
CREATE TABLE public.category (
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(25) NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.category ADD CONSTRAINT category_pkey PRIMARY KEY (category_id);
ALTER TABLE public.category OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.category TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.category TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.category TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.category TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.category TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.address...';END$$;
CREATE TABLE public.address (
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address character varying(50) NOT NULL,
    address2 character varying(50),
    district character varying(20) NOT NULL,
    city_id integer NOT NULL,
    postal_code character varying(10),
    phone character varying(20) NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.address ADD CONSTRAINT address_pkey PRIMARY KEY (address_id);
ALTER TABLE public.address OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.address TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.address TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.address TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.address TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.address TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.actor...';END$$;
CREATE TABLE public.actor (
    actor_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(45) NOT NULL,
    last_name character varying(45) NOT NULL,
    last_update timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.actor ADD CONSTRAINT actor_pkey PRIMARY KEY (actor_id);
ALTER TABLE public.actor OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.actor TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.actor TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.actor TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.actor TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.actor TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.sales_by_film_category...';END$$;
CREATE VIEW public.sales_by_film_category (category, total_sales) AS SELECT c.name AS category,
    sum(p.amount) AS total_sales
   FROM ((((public.payment p
     JOIN public.rental r ON ((p.rental_id = r.rental_id)))
     JOIN public.inventory i ON ((r.inventory_id = i.inventory_id)))
     JOIN public.film_category fc ON ((i.film_id = fc.film_id)))
     JOIN public.category c ON ((fc.category_id = c.category_id)))
  GROUP BY c.name;
ALTER VIEW public.sales_by_film_category OWNER TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE /* VIEW */ public.sales_by_film_category TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE /* VIEW */ public.sales_by_film_category TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE /* VIEW */ public.sales_by_film_category TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE /* VIEW */ public.sales_by_film_category TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE /* VIEW */ public.sales_by_film_category TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.customer_list...';END$$;
CREATE VIEW public.customer_list (id, name, address, "zip code", phone, city, country, notes, sid) AS SELECT cu.customer_id AS id,
    (((cu.first_name)::text || ' '::text) || (cu.last_name)::text) AS name,
    (a.address)::text AS address,
    (a.postal_code)::text AS "zip code",
    (a.phone)::text AS phone,
    (city.city)::text AS city,
    (country.country)::text AS country,
        CASE
            WHEN cu.activebool THEN 'active'::text
            ELSE ''::text
        END AS notes,
    cu.store_id AS sid
   FROM (((public.customer cu
     JOIN public.address a ON ((cu.address_id = a.address_id)))
     JOIN public.city city ON ((a.city_id = city.city_id)))
     JOIN public.country country ON ((city.country_id = country.country_id)));
ALTER VIEW public.customer_list OWNER TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE /* VIEW */ public.customer_list TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE /* VIEW */ public.customer_list TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE /* VIEW */ public.customer_list TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE /* VIEW */ public.customer_list TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE /* VIEW */ public.customer_list TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.last_updated()...';END$$;
CREATE FUNCTION public.last_updated()
RETURNS trigger
LANGUAGE plpgsql
AS $_$
BEGIN
    NEW.last_update = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$_$;
ALTER FUNCTION public.last_updated() OWNER TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.inventory_in_stock(integer)...';END$$;
CREATE FUNCTION public.inventory_in_stock(IN p_inventory_id integer)
RETURNS boolean
LANGUAGE plpgsql
AS $_$
DECLARE
    v_rentals INTEGER;
    v_out INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_rentals FROM public.rental WHERE inventory_id = p_inventory_id;
    IF v_rentals = 0 THEN
      RETURN TRUE;
    END IF;

    SELECT COUNT(*) INTO v_out FROM public.inventory, public.rental 
    WHERE inventory.inventory_id = rental.inventory_id 
      AND rental.inventory_id = p_inventory_id 
      AND rental.return_date IS NULL;

    IF v_out > 0 THEN
      RETURN FALSE;
    ELSE
      RETURN TRUE;
    END IF;
END;
$_$;
ALTER FUNCTION public.inventory_in_stock(IN p_inventory_id integer) OWNER TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.grant_usage_on_new_schema()...';END$$;
CREATE FUNCTION public.grant_usage_on_new_schema()
RETURNS event_trigger
LANGUAGE plpgsql
AS $_$
DECLARE
    db_id TEXT;
    obj record;
BEGIN
    SELECT oid FROM pg_catalog.pg_database WHERE datname = pg_catalog.current_database() INTO db_id;
    FOR obj IN (SELECT * FROM pg_catalog.pg_event_trigger_ddl_commands() AS ddl
                WHERE ddl.object_type = 'schema' AND ddl.object_identity != '__db_system')
    LOOP
        BEGIN
            EXECUTE pg_catalog.format('GRANT USAGE ON SCHEMA %s TO "databricks_gateway"', obj.object_identity);
            EXECUTE pg_catalog.format('GRANT ALL ON SCHEMA %s TO "databricks_superuser" WITH GRANT OPTION', obj.object_identity);
        EXCEPTION
            WHEN others THEN
                RAISE WARNING 'An error occurred while granting system permissions on schema %: %', obj.object_identity, SQLERRM;
        END;

        BEGIN
            EXECUTE pg_catalog.format('GRANT USAGE ON SCHEMA %s TO databricks_reader_%s', obj.object_identity, db_id);
            EXECUTE pg_catalog.format('GRANT USAGE, CREATE ON SCHEMA %s TO databricks_writer_%s', obj.object_identity, db_id);
        EXCEPTION
            WHEN others then
                RAISE WARNING 'An error occurred while granting system permissions on schema %: %', obj.object_identity, SQLERRM;
        END;
    END LOOP;
END;
$_$;
ALTER FUNCTION public.grant_usage_on_new_schema() OWNER TO cloud_admin;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.grant_select_on_new_objects()...';END$$;
CREATE FUNCTION public.grant_select_on_new_objects()
RETURNS event_trigger
LANGUAGE plpgsql
AS $_$
DECLARE
    db_id TEXT;
    obj record;
    schema_name TEXT;
    object_name TEXT;
BEGIN
    SELECT oid from pg_catalog.pg_database WHERE datname = pg_catalog.current_database() INTO db_id;
    FOR obj IN (SELECT * FROM pg_catalog.pg_event_trigger_ddl_commands() AS ddl
                WHERE ddl.object_type IN ('table', 'view', 'materialized view')
                AND ddl.object_identity != '__db_system')
    LOOP
        BEGIN
            EXECUTE pg_catalog.format('GRANT SELECT ON %s TO "databricks_gateway"', obj.object_identity);
            EXECUTE pg_catalog.format('GRANT ALL ON %s TO "databricks_superuser" WITH GRANT OPTION', obj.object_identity);
        EXCEPTION
            WHEN others THEN
                RAISE WARNING 'An error occurred while granting system permissions on object %: %', obj.object_identity, SQLERRM;
        END;

        BEGIN
            EXECUTE pg_catalog.format('GRANT SELECT ON %s TO databricks_reader_%s', obj.object_identity, db_id);
        EXCEPTION
            WHEN others THEN
                RAISE WARNING 'An error occurred while granting system permissions on object %: %', obj.object_identity, SQLERRM;
        END;
    END LOOP;
END;
$_$;
ALTER FUNCTION public.grant_select_on_new_objects() OWNER TO cloud_admin;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.grant_all_on_new_sequences()...';END$$;
CREATE FUNCTION public.grant_all_on_new_sequences()
RETURNS event_trigger
LANGUAGE plpgsql
AS $_$
DECLARE
    db_id TEXT;
    obj record;
    schema_name TEXT;
    object_name TEXT;
BEGIN
    SELECT oid FROM pg_catalog.pg_database WHERE datname = pg_catalog.current_database() INTO db_id;
    FOR obj IN (SELECT * FROM pg_catalog.pg_event_trigger_ddl_commands() AS ddl
                WHERE ddl.object_type = 'sequence'
                AND ddl.object_identity != '__db_system')
    LOOP
        BEGIN
            EXECUTE pg_catalog.format('GRANT ALL ON %s TO "databricks_superuser" WITH GRANT OPTION', obj.object_identity);
        EXCEPTION
            WHEN others THEN
                RAISE WARNING 'An error occurred while granting system permissions on object %: %', obj.object_identity, SQLERRM;
        END;
    END LOOP;
END;
$_$;
ALTER FUNCTION public.grant_all_on_new_sequences() OWNER TO cloud_admin;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public._group_concat(text, text)...';END$$;
CREATE FUNCTION public._group_concat(IN text, IN text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $_$
SELECT CASE
  WHEN $1 IS NULL OR $1 = '' THEN $2
  WHEN $2 IS NULL OR $2 = '' THEN $1
  ELSE $1 || ', ' || $2
END;
$_$;
ALTER FUNCTION public._group_concat(IN text, IN text) OWNER TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.group_concat(text)...';END$$;
CREATE AGGREGATE public.group_concat(text) (
    SFUNC = public._group_concat,
    STYPE = text
);
ALTER AGGREGATE public.group_concat(text) OWNER TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.store.store_address_id_fkey...';END$$;
ALTER TABLE public.store ADD CONSTRAINT store_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.address (address_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.staff.staff_store_id_fkey...';END$$;
ALTER TABLE public.staff ADD CONSTRAINT staff_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.store (store_id) ON UPDATE CASCADE ON DELETE SET NULL;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.staff.staff_address_id_fkey...';END$$;
ALTER TABLE public.staff ADD CONSTRAINT staff_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.address (address_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.rental.rental_staff_id_fkey...';END$$;
ALTER TABLE public.rental ADD CONSTRAINT rental_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff (staff_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.rental.rental_inventory_id_fkey...';END$$;
ALTER TABLE public.rental ADD CONSTRAINT rental_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory (inventory_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.rental.rental_customer_id_fkey...';END$$;
ALTER TABLE public.rental ADD CONSTRAINT rental_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer (customer_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.payment.payment_staff_id_fkey...';END$$;
ALTER TABLE public.payment ADD CONSTRAINT payment_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff (staff_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.payment.payment_rental_id_fkey...';END$$;
ALTER TABLE public.payment ADD CONSTRAINT payment_rental_id_fkey FOREIGN KEY (rental_id) REFERENCES public.rental (rental_id) ON UPDATE CASCADE ON DELETE SET NULL;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.payment.payment_customer_id_fkey...';END$$;
ALTER TABLE public.payment ADD CONSTRAINT payment_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer (customer_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.inventory.inventory_store_id_fkey...';END$$;
ALTER TABLE public.inventory ADD CONSTRAINT inventory_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.store (store_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film_category.film_category_category_id_fkey...';END$$;
ALTER TABLE public.film_category ADD CONSTRAINT film_category_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category (category_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film_actor.film_actor_actor_id_fkey...';END$$;
ALTER TABLE public.film_actor ADD CONSTRAINT film_actor_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actor (actor_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.customer.customer_store_id_fkey...';END$$;
ALTER TABLE public.customer ADD CONSTRAINT customer_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.store (store_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.customer.customer_address_id_fkey...';END$$;
ALTER TABLE public.customer ADD CONSTRAINT customer_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.address (address_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.city.city_country_id_fkey...';END$$;
ALTER TABLE public.city ADD CONSTRAINT city_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.country (country_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.address.address_city_id_fkey...';END$$;
ALTER TABLE public.address ADD CONSTRAINT address_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.city (city_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.playing_with_lakebase_id_seq...';END$$;
CREATE SEQUENCE public.playing_with_lakebase_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.playing_with_lakebase_id_seq OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.playing_with_lakebase...';END$$;
CREATE TABLE public.playing_with_lakebase (
    id integer NOT NULL DEFAULT nextval('public.playing_with_lakebase_id_seq'::regclass),
    name text NOT NULL,
    value real
);
ALTER TABLE public.playing_with_lakebase ADD CONSTRAINT playing_with_lakebase_pkey PRIMARY KEY (id);
ALTER TABLE public.playing_with_lakebase OWNER TO stephanie."herr@red-gate".com;
INSERT INTO public.playing_with_lakebase(id, name, value) OVERRIDING SYSTEM VALUE VALUES
(1, 'c4ca4238a0', '0.4640946'),
(2, 'c81e728d9d', '0.71552026'),
(3, 'eccbc87e4b', '0.2814052'),
(4, 'a87ff679a2', '0.23061368'),
(5, 'e4da3b7fbb', '0.8133272'),
(6, '1679091c5a', '0.36934167'),
(7, '8f14e45fce', '0.9007749'),
(8, 'c9f0f895fb', '0.76468515'),
(9, '45c48cce2e', '0.7642244'),
(10, 'd3d9446802', '0.35960853')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, value = EXCLUDED.value;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.playing_with_lakebase TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.playing_with_lakebase TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.playing_with_lakebase TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.playing_with_lakebase TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.playing_with_lakebase TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Altering public.playing_with_lakebase_id_seq...';END$$;
ALTER SEQUENCE public.playing_with_lakebase_id_seq OWNED BY public.playing_with_lakebase.id;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.year...';END$$;
CREATE DOMAIN public.year AS integer;
ALTER DOMAIN public.year OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.mpaa_rating...';END$$;
CREATE TYPE public.mpaa_rating AS ENUM ('G', 'PG', 'PG-13', 'R', 'NC-17');
ALTER TYPE public.mpaa_rating OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film...';END$$;
CREATE TABLE public.film (
    film_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying(255) NOT NULL,
    description text,
    release_year public.year,
    language_id integer NOT NULL,
    original_language_id integer,
    rental_duration smallint NOT NULL DEFAULT 3,
    rental_rate numeric(4,2) NOT NULL DEFAULT 4.99,
    length smallint,
    replacement_cost numeric(5,2) NOT NULL DEFAULT 19.99,
    rating public.mpaa_rating DEFAULT 'G'::public.mpaa_rating,
    last_update timestamp with time zone NOT NULL DEFAULT now(),
    special_features text[],
    fulltext tsvector NOT NULL
);
ALTER TABLE public.film ADD CONSTRAINT film_pkey PRIMARY KEY (film_id);
ALTER TABLE public.film OWNER TO stephanie."herr@red-gate".com;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.film TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.film TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE public.film TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE public.film TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE public.film TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film_list...';END$$;
CREATE VIEW public.film_list (fid, title, description, category, price, length, rating, actors) AS SELECT film.film_id AS fid,
    film.title,
    film.description,
    category.name AS category,
    film.rental_rate AS price,
    film.length,
    film.rating,
    public.group_concat((((actor.first_name)::text || ' '::text) || (actor.last_name)::text)) AS actors
   FROM ((((public.category
     JOIN public.film_category ON ((category.category_id = film_category.category_id)))
     JOIN public.film ON ((film_category.film_id = film.film_id)))
     JOIN public.film_actor ON ((film.film_id = film_actor.film_id)))
     JOIN public.actor ON ((film_actor.actor_id = actor.actor_id)))
  GROUP BY film.film_id, film.title, film.description, category.name, film.rental_rate, film.length, film.rating;
ALTER VIEW public.film_list OWNER TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to "stephanie.herr@red-gate.com"...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE /* VIEW */ public.film_list TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to app_user...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE /* VIEW */ public.film_list TO app_user;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_gateway...';END$$;
GRANT SELECT ON TABLE /* VIEW */ public.film_list TO databricks_gateway;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_superuser...';END$$;
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLE /* VIEW */ public.film_list TO databricks_superuser;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Granting privilege(s) to databricks_reader_16403...';END$$;
GRANT SELECT ON TABLE /* VIEW */ public.film_list TO databricks_reader_16403;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.get_customer_balance(integer, timestamp with time zone)...';END$$;
CREATE FUNCTION public.get_customer_balance(IN p_customer_id integer, IN p_effective_date timestamp with time zone)
RETURNS numeric
LANGUAGE plpgsql
AS $_$
       -- Calculates total fees and subtracts previous payment amounts
DECLARE
    v_rentfees NUMERIC; 
    v_overdues NUMERIC; 
    v_payments NUMERIC; 
BEGIN
    SELECT COALESCE(SUM(film.rental_rate),0) INTO v_rentfees
    FROM public.film, public.inventory, public.rental
    WHERE film.film_id = inventory.film_id
      AND inventory.inventory_id = rental.inventory_id
      AND rental.customer_id = p_customer_id
      AND rental.rental_date <= p_effective_date;

    SELECT COALESCE(SUM(CASE WHEN (rental.return_date > (rental.rental_date + (film.rental_duration * EXTRA -1))) THEN (film.rental_rate) ELSE 0 END),0) INTO v_overdues
    FROM public.film, public.inventory, public.rental
    WHERE film.film_id = inventory.film_id
      AND inventory.inventory_id = rental.inventory_id
      AND rental.customer_id = p_customer_id
      AND rental.rental_date <= p_effective_date;

    SELECT COALESCE(SUM(payment.amount),0) INTO v_payments
    FROM public.payment
    WHERE payment.customer_id = p_customer_id
      AND payment.payment_date <= p_effective_date;

    RETURN v_rentfees + v_overdues - v_payments;
END;
$_$;
ALTER FUNCTION public.get_customer_balance(IN p_customer_id integer, IN p_effective_date timestamp with time zone) OWNER TO "stephanie.herr@red-gate.com";


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.inventory.inventory_film_id_fkey...';END$$;
ALTER TABLE public.inventory ADD CONSTRAINT inventory_film_id_fkey FOREIGN KEY (film_id) REFERENCES public.film (film_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film_category.film_category_film_id_fkey...';END$$;
ALTER TABLE public.film_category ADD CONSTRAINT film_category_film_id_fkey FOREIGN KEY (film_id) REFERENCES public.film (film_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film_actor.film_actor_film_id_fkey...';END$$;
ALTER TABLE public.film_actor ADD CONSTRAINT film_actor_film_id_fkey FOREIGN KEY (film_id) REFERENCES public.film (film_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film.film_original_language_id_fkey...';END$$;
ALTER TABLE public.film ADD CONSTRAINT film_original_language_id_fkey FOREIGN KEY (original_language_id) REFERENCES public.language (language_id) ON UPDATE CASCADE ON DELETE RESTRICT;


DO LANGUAGE plpgsql $$BEGIN RAISE NOTICE 'Creating public.film.film_language_id_fkey...';END$$;
ALTER TABLE public.film ADD CONSTRAINT film_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language (language_id) ON UPDATE CASCADE ON DELETE RESTRICT;

